# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
# Upgrade pip and increase timeout for large packages like TensorFlow
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --timeout=800 -r requirements.txt

# Copy the application code into the container at /app
COPY StockMarketPredictor.py .
COPY data_collector.py .

# The data_collector.py script will create the data/ directory if needed,
# so we don't explicitly copy it here anymore if it's generated by the script.
# If you have pre-existing base data files you want to include,
# you would add: COPY data/ ./data/

# Create the models directory (the script will write to it)
RUN mkdir models

# Define the command to run your applications in sequence
CMD ["sh", "-c", "python data_collector.py && python StockMarketPredictor.py"] 